[project]
name = "pafsk8"
version = "0.1.0"
description = "Pafsk8 using crewAI"
authors = [{ name = "Alex", email = "as00paf@gmail.com" }]
requires-python = ">=3.10,<3.14"
dependencies = [
    "crewai[google-genai,litellm,tools]==1.10.1",
    "python-dotenv>=1.0.0",
]

[project.scripts]
pafsk8 = "pafsk8.main:run"
run_crew = "pafsk8.main:run"
train = "pafsk8.main:train"
replay = "pafsk8.main:replay"
test = "pafsk8.main:test"
run_with_trigger = "pafsk8.main:run_with_trigger"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
