[versions]
kotlin = "2.0.21"
lwjgl = "3.3.6"
libbulletjme = "22.0.3"
snaploader = "1.0.0-stable"
joml = "1.10.8"
joml-primitives = "1.10.0"
imgui = "1.90.0"
kotlinx-coroutines = "1.8.0"
kotlinx-serialization = "1.7.3"
junit = "5.10.0"
mockk = "1.13.12"
koin = "3.5.6"

[libraries]
lwjgl-bom = { group = "org.lwjgl", name = "lwjgl-bom", version.ref = "lwjgl" }
lwjgl = { group = "org.lwjgl", name = "lwjgl" }
lwjgl-assimp = { group = "org.lwjgl", name = "lwjgl-assimp" }
lwjgl-glfw = { group = "org.lwjgl", name = "lwjgl-glfw" }
lwjgl-openal = { group = "org.lwjgl", name = "lwjgl-openal" }
lwjgl-opengl = { group = "org.lwjgl", name = "lwjgl-opengl" }
lwjgl-stb = { group = "org.lwjgl", name = "lwjgl-stb" }
lwjgl-tinyfd = { group = "org.lwjgl", name = "lwjgl-tinyfd" }

libbulletjme = { group = "com.github.stephengold", name = "Libbulletjme-Windows64", version.ref = "libbulletjme" }

snaploader = { group = "io.github.electrostat-lab", name = "snaploader", version.ref = "snaploader" }
joml = { group = "org.joml", name = "joml", version.ref = "joml" }
joml-primitives = { group = "org.joml", name = "joml-primitives", version.ref = "joml-primitives" }
imgui-binding = { group = "io.github.spair", name = "imgui-java-binding", version.ref = "imgui" }
imgui-lwjgl3 = { group = "io.github.spair", name = "imgui-java-lwjgl3", version.ref = "imgui" }
imgui-natives-windows = { group = "io.github.spair", name = "imgui-java-natives-windows", version.ref = "imgui" }
kotlinx-coroutines-core = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-test = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-test", version.ref = "kotlinx-coroutines" }
kotlinx-serialization-json = { group = "org.jetbrains.kotlinx", name = "kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
junit-jupiter = { group = "org.junit.jupiter", name = "junit-jupiter", version.ref = "junit" }
mockk = { group = "io.mockk", name = "mockk", version.ref = "mockk" }

koin-core = { group = "io.insert-koin", name = "koin-core", version.ref = "koin" }
koin-test = { group = "io.insert-koin", name = "koin-test", version.ref = "koin" }
koin-test-junit5 = { group = "io.insert-koin", name = "koin-test-junit5", version.ref = "koin" }

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }