trick.kickflip=Kickflip
trick.heelflip=Heelflip
trick.shoveit=Shove-it
trick.360shoveit=360 Shove-it
trick.ollie=Ollie
trick.backflip=Backflip
trick.frontflip=Frontflip
trick.bs=BS %d
trick.fs=FS %d

stance.fakie=Fakie
stance.nollie=Nollie
stance.switch=Switch
